//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources11 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources11() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApp1.Properties.Resources11", typeof(Resources11).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   aaaaaaaaa に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String1_1 {
            get {
                return ResourceManager.GetString("String1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String1_10 {
            get {
                return ResourceManager.GetString("String1_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String1_11 {
            get {
                return ResourceManager.GetString("String1_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String1_12 {
            get {
                return ResourceManager.GetString("String1_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String1_13 {
            get {
                return ResourceManager.GetString("String1_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String1_14 {
            get {
                return ResourceManager.GetString("String1_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String1_15 {
            get {
                return ResourceManager.GetString("String1_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String1_16 {
            get {
                return ResourceManager.GetString("String1_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String1_17 {
            get {
                return ResourceManager.GetString("String1_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String1_18 {
            get {
                return ResourceManager.GetString("String1_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String1_19 {
            get {
                return ResourceManager.GetString("String1_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   bbbbb に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String1_2 {
            get {
                return ResourceManager.GetString("String1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String1_20 {
            get {
                return ResourceManager.GetString("String1_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String1_21 {
            get {
                return ResourceManager.GetString("String1_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String1_22 {
            get {
                return ResourceManager.GetString("String1_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String1_23 {
            get {
                return ResourceManager.GetString("String1_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String1_24 {
            get {
                return ResourceManager.GetString("String1_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String1_25 {
            get {
                return ResourceManager.GetString("String1_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String1_26 {
            get {
                return ResourceManager.GetString("String1_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   11 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String1_27 {
            get {
                return ResourceManager.GetString("String1_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String1_28 {
            get {
                return ResourceManager.GetString("String1_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String1_29 {
            get {
                return ResourceManager.GetString("String1_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   cccccc に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String1_3 {
            get {
                return ResourceManager.GetString("String1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String1_30 {
            get {
                return ResourceManager.GetString("String1_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String1_31 {
            get {
                return ResourceManager.GetString("String1_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   dddd に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String1_4 {
            get {
                return ResourceManager.GetString("String1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   aa に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String1_5 {
            get {
                return ResourceManager.GetString("String1_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   q に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String1_6 {
            get {
                return ResourceManager.GetString("String1_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   q に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String1_7 {
            get {
                return ResourceManager.GetString("String1_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   q に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String1_8 {
            get {
                return ResourceManager.GetString("String1_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String1_9 {
            get {
                return ResourceManager.GetString("String1_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String2_1 {
            get {
                return ResourceManager.GetString("String2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String2_2 {
            get {
                return ResourceManager.GetString("String2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String2_3 {
            get {
                return ResourceManager.GetString("String2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   22 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String2_4 {
            get {
                return ResourceManager.GetString("String2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String2_5 {
            get {
                return ResourceManager.GetString("String2_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   3 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String3_1 {
            get {
                return ResourceManager.GetString("String3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   3 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String3_2 {
            get {
                return ResourceManager.GetString("String3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   3 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String3_3 {
            get {
                return ResourceManager.GetString("String3_3", resourceCulture);
            }
        }
    }
}
